---
title: "Life Calculated by the Phone"
author: "Shuyang Huang & Jonghoon Park"
date: "3/5/2021"
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)
```

```{r, include = F}
setwd("~/Desktop/MArch-Columbia/4 - ADR 2/Assignment 1C/Life-in-the-Phone")
dat <- openxlsx::read.xlsx("/Users/Young/Desktop/MArch-Columbia/4 - ADR 2/Assignment 1C/Life-in-the-Phone/ADR2 - 2A - DEAR SYSTEMS .xlsx", sheet = 2)

library(tidyverse)
library(plotly)

dat <- gather(dat, sleep:entertainment, key = "type", value = "value")
```
# 2/8 - 2/14

```{r, echo = FALSE}
dat1 <- dat %>% filter(week == 1)

dat1$id <- seq_len(nrow(dat1))
ds <- replicate(2, dat1, simplify = F)
ds[[2]]$value <- 0
d <- ds %>%
  bind_rows() %>%
  group2NA("id", "name")

plot_ly(color = ~factor(name), showlegend = F) %>%
  add_markers(data = dat1, x=~day, y=~type, z=~value) %>%
  add_paths(data = d, x=~day, y=~type, z=~value)%>% 
  layout(
    title = "",
    scene = list(
      xaxis = list(title = "DAY"),
      yaxis = list(title = "ACTIVITY"),
      zaxis = list(title = "MINUTES")
    ))

```

# 2/15 - 2/21

```{r, echo = FALSE}
dat2 <- dat %>% filter(week == 2)

dat2$id <- seq_len(nrow(dat2))
ds <- replicate(2, dat2, simplify = F)
ds[[2]]$value <- 0
d <- ds %>%
  bind_rows() %>%
  group2NA("id", "name")

plot_ly(color = ~factor(name), showlegend = F) %>%
  add_markers(data = dat2, x=~day, y=~type, z=~value) %>%
  add_paths(data = d, x=~day, y=~type, z=~value)%>% 
  layout(
    title = "",
    scene = list(
      xaxis = list(title = "DAY"),
      yaxis = list(title = "ACTIVITY"),
      zaxis = list(title = "MINUTES")
    ))

```

# 2/22 - 2/28

```{r, echo = FALSE}
dat3 <- dat %>% filter(week == 3)

dat3$id <- seq_len(nrow(dat3))
ds <- replicate(2, dat3, simplify = F)
ds[[2]]$value <- 0
d <- ds %>%
  bind_rows() %>%
  group2NA("id", "name")

plot_ly(color = ~factor(name), showlegend = F) %>%
  add_markers(data = dat3, x=~day, y=~type, z=~value) %>%
  add_paths(data = d, x=~day, y=~type, z=~value)%>% 
  layout(
    title = "",
    scene = list(
      xaxis = list(title = "DAY"),
      yaxis = list(title = "ACTIVITY"),
      zaxis = list(title = "MINUTES")
    ))

```

# 3/1 - 

```{r, echo = FALSE}
dat4 <- dat %>% filter(week == 4)

dat4$id <- seq_len(nrow(dat4))
ds <- replicate(2, dat4, simplify = F)
ds[[2]]$value <- 0
d <- ds %>%
  bind_rows() %>%
  group2NA("id", "name")

plot_ly(color = ~factor(name), showlegend = F) %>%
  add_markers(data = dat4, x=~day, y=~type, z=~value) %>%
  add_paths(data = d, x=~day, y=~type, z=~value)%>% 
  layout(
    title = "",
    scene = list(
      xaxis = list(title = "DAY"),
      yaxis = list(title = "ACTIVITY"),
      zaxis = list(title = "MINUTES")
    ))

```

